export const FrontendRoutes = {
  HOME: '/',
  NEWORDERS: '/new-orders',
  ORDERLIST: '/order-list',
  COMPLETEDORDERS: '/completed-orders',
  CANCELLEDORDERS: '/cancelled-orders',
  ORDERVERIFY: '/new-orders/order-verify',
  ORDERTRACKING: '/order-list/order-tracking',
  PRODUCTLIST: '/product-list',
  ADDPRODUCT: '/product-list/add-product',
  VIEWPRODUCT: '/product-list/view-product',
  CATEGORYLIST: '/category-list',
  ATTRIBUTE: '/attribute',
  ATTRIBTUE_BRAND: '/attribute',
  ATTRIBTUE_DISCOUNT: '/attribute/discount',
  ATTRIBTUE_VOUCHER: '/attribute/voucher',
  CUSTOMER: '/customerlist',
  VIEWCUSTOMER: '/customerlist/customerview',
  ASSIGN_DELIVERY_PERSON: '/assign-delivery-person',

  // TRANSACTION: "/transaction",
  ALLTRANSACTION: '/transaction',
  VERIFY_TRANSACTION: '/verify-transaction',
  LOGIN: '/login',
  REFERALMANAGEMENT: '/referalmanagement',
  LOYALTYPOINTS: '/loyalty-points',
  POINTSCONFIGURATION: '/points-configuration',
  PURCHASEREWARD: '/points-configuration',
  REWARDREFERAL: '/points-configuration/reward-referal',
  DELIVERY_PERSON_LIST: '/delivery-person-list',
  DELIVERY_PERSON_REQUEST: '/delivery-person-request',
  DELIVERY_PERSON_REQUEST_ALL: '/delivery-person-request',
  DELIVERY_PERSON_REQUEST_PENDING: '/delivery-person-request/pending',
  DELIVERY_PERSON_REQUEST_APPROVED: '/delivery-person-request/approved',
  DELIVERY_PERSON_REQUEST_REJECTED: '/delivery-person-request/rejected',
  DELIVERY_LIVE_OVERVIEW: '/delivery-live-overview',
  STOCK_OVERVIEW: '/stock-overview',
  SUPPLIER: '/supplier',
  SUPPLIER_List: '/supplier-list',
  PURCHASE_HISTORY: '/purchase-history',
  SUPPLIER_DETAILS: '/supplier-details',

  PURCHASE: '/purchase',
  PURCHASEDETAILS: '/purchasedetails',
  EXPENSES: '/expenses',
  PROFITLOSS: '/profitloss',
  CASHFLOW: '/cashflow',
  DELIVERYSETTLEMENT: '/delivery-settlement',
  DELIVERYCONFIGURATION: '/delivery-configuration',
  DELIVERY_Fee: '/delivery-configuration',
  DELIVERY_MINIMUM: '/delivery-configuration/delivery-mimimumorder',
  DELIVERY_Free: '/delivery-configuration/delivery-free',
  SALESREPORT: '/sales-report',
  SALES_PRODUCT_REPORT: '/sales-report',
  SALES_CATEOGORY_REPORT: '/sales-report/category-wise',
  SALES_BRAND_REPORT: '/sales-report/brand-wise',
  DELIVERYREPORT: '/delivery-report',
  ORDERREPORT: '/order-report',
  STOCKREPORT: '/order-stock',
  BANNER: '/banner',
  TOPBANNER: '/banner',
  BOTTOMBANNER: '/banner/bottom-banner',

  LOGOUT: '#log-out',
};
